/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Minimax;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;

/**
 *
 * @author samuel
 */
public class VistaInicial extends JFrame {

	private CtrlPresentacion cp;
	/**
	 * Creates new form VistaInicial
	 */
	public VistaInicial(CtrlPresentacion cp) {

		this.cp = cp;
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		botonSalir = new JButton();
		botonJugar = new JButton();
		textoNombreUser = new JLabel();
		FieldNombreUser = new JTextField();
		LayerOpciones = new JLayeredPane();
		color = new JComboBox<>();
		EmpezarTirandoCheck = new JCheckBox();

		setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
		setTitle("Inicio");
		setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
		setName("frame"); // NOI18N

		botonSalir.setText("Salir");
		botonSalir.addActionListener(this::botonSalirActionPerformed);

		botonJugar.setText("Jugar");
		botonJugar.addActionListener(this::botonJugarActionPerformed);

		textoNombreUser.setHorizontalAlignment(SwingConstants.CENTER);
		textoNombreUser.setText("Nombre de usuario:");

		LayerOpciones.setBorder(BorderFactory.createTitledBorder("Opciones"));

		color.setModel(new DefaultComboBoxModel<>(new String[] { "Cruz", "Circulo" }));
		color.addActionListener(this::colorActionPerformed);

		EmpezarTirandoCheck.setSelected(true);
		EmpezarTirandoCheck.setText("Empezar Tirando");
		EmpezarTirandoCheck.addActionListener(this::EmpezarTirandoCheckActionPerformed);

		LayerOpciones.setLayer(color, JLayeredPane.DEFAULT_LAYER);
		LayerOpciones.setLayer(EmpezarTirandoCheck, JLayeredPane.DEFAULT_LAYER);

		GroupLayout LayerOpcionesLayout = new GroupLayout(LayerOpciones);
		LayerOpciones.setLayout(LayerOpcionesLayout);
		LayerOpcionesLayout.setHorizontalGroup(
			LayerOpcionesLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
				.addGroup(LayerOpcionesLayout.createSequentialGroup()
					.addGroup(LayerOpcionesLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
						.addComponent(EmpezarTirandoCheck)
						.addComponent(color, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
					.addGap(0, 38, Short.MAX_VALUE))
		);
		LayerOpcionesLayout.setVerticalGroup(
			LayerOpcionesLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
				.addGroup(LayerOpcionesLayout.createSequentialGroup()
					.addContainerGap()
					.addComponent(EmpezarTirandoCheck)
					.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
					.addComponent(color, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
					.addContainerGap())
		);

		GroupLayout layout = new GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
			layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
				.addGroup(layout.createSequentialGroup()
					.addContainerGap()
					.addComponent(textoNombreUser, GroupLayout.PREFERRED_SIZE, 147, GroupLayout.PREFERRED_SIZE)
					.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
					.addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
						.addComponent(LayerOpciones, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
						.addComponent(FieldNombreUser, GroupLayout.PREFERRED_SIZE, 184, GroupLayout.PREFERRED_SIZE))
					.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
					.addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
						.addComponent(botonSalir, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 54, GroupLayout.PREFERRED_SIZE)
						.addComponent(botonJugar, GroupLayout.Alignment.TRAILING))
					.addContainerGap())
		);
		layout.setVerticalGroup(
			layout.createParallelGroup(GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
					.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
					.addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
						.addComponent(textoNombreUser, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
						.addComponent(FieldNombreUser, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
						.addComponent(botonJugar, GroupLayout.Alignment.TRAILING))
					.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
					.addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
						.addComponent(LayerOpciones, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
						.addComponent(botonSalir, GroupLayout.Alignment.TRAILING))
					.addContainerGap())
		);

		pack();
		setLocationRelativeTo(null);
	}// </editor-fold>//GEN-END:initComponents

	private void botonSalirActionPerformed(ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
		System.exit(0);
	}//GEN-LAST:event_botonSalirActionPerformed

	private void botonJugarActionPerformed(ActionEvent evt) {//GEN-FIRST:event_botonJugarActionPerformed

		cp.setUsuarioJuegaCruz(color.getSelectedIndex()==0);
		cp.iniciarPartida(FieldNombreUser.getText(),color.getSelectedIndex(),EmpezarTirandoCheck.isSelected());
		cp.sincronizacion_VistaInicial_a_VistaPartida();
		//JOptionPane.showMessageDialog(null,"Has introducido: Nombre -> ["+FieldNombreUser.getText()
		//	+"] color ficha -> ["+color.getSelectedIndex()+"] Empezar? ["+EmpezarTirandoCheck.isSelected()+"]");
	}//GEN-LAST:event_botonJugarActionPerformed

	private void colorActionPerformed(ActionEvent evt) {//GEN-FIRST:event_colorActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_colorActionPerformed

	private void EmpezarTirandoCheckActionPerformed(ActionEvent evt) {//GEN-FIRST:event_EmpezarTirandoCheckActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_EmpezarTirandoCheckActionPerformed

	public void hacerlaVisible(){

		this.setVisible(true);
	}

	public void hacerlaInvisible(){

		this.setVisible(false);
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private JCheckBox EmpezarTirandoCheck;
	private JTextField FieldNombreUser;
	private JLayeredPane LayerOpciones;
	private JButton botonJugar;
	private JButton botonSalir;
	private JComboBox<String> color;
	private JLabel textoNombreUser;
	// End of variables declaration//GEN-END:variables
}
